### ISSUE TITLE
doesn't build on macos

### ISSUE THREAD

**Issue by olilarkin** [prime31/zig-upaya#1]
beast:zig-upaya oli$ zig build
Semantic Analysis [1876/2781] ./src/build.zig:42:32: error: expected type '[]std.build.Pkg', found '*const [4]std.build.Pkg'
        .dependencies = &[_]Pkg{stb_image, filebrowser, sokol, imgui},
                               ^

**Comment by jamesb93** [comment]
Try uninstalling zig and `brew install zig --HEAD`

**Comment by olilarkin** [comment]
thanks jamesb93

now...

beast:zig-upaya oli$ zig build
Build Dependencies...c++ [2] Compile C Objects [37/37] vector.cpp...ld: unknown option: -error-limit
docking...The following command exited with error code 1:
/usr/local/Cellar/zig/HEAD-c0654d2_1/bin/zig build-exe /Users/oli/Dev/zig-upaya/examples/docking.zig --library c --library c++ --c-source -std=c99 -ObjC -fobjc-arc /Users/oli/Dev/zig-upaya/src/deps/sokol/compile_sokol.c --object /Users/oli/Dev/zig-upaya/zig-cache/o/A5_j95Je2QJZLHUaf2eHlApbyI7D30JAVYj1YvXgCg5gsZKvnCtTiyGvDEcJc35u/libStbImage.a --library c++ --c-source -Wno-return-type-c-linkage /Users/oli/Dev/zig-upaya/src/deps/imgui/cimgui/imgui/imgui.cpp --c-source -Wno-return-type-c-linkage /Users/oli/Dev/zig-upaya/src/deps/imgui/cimgui/imgui/imgui_demo.cpp --c-source -Wno-return-type-c-linkage /Users/oli/Dev/zig-upaya/src/deps/imgui/cimgui/imgui/imgui_draw.cpp --c-source -Wno-return-type-c-linkage /Users/oli/Dev/zig-upaya/src/deps/imgui/cimgui/imgui/imgui_widgets.cpp --c-source -Wno-return-type-c-linkage /Users/oli/Dev/zig-upaya/src/deps/imgui/cimgui/cimgui.cpp --object /Users/oli/Dev/zig-upaya/zig-cache/o/UoCqK02QosyrzmvgOMKuum0-DGiKQYi-5XtTGFFxjszu9TYLire5Ns_JTFecxj5x/libFileBrowser.a --cache-dir /Users/oli/Dev/zig-upaya/zig-cache --name docking --pkg-begin aya /Users/oli/Dev/zig-upaya/src/aya.zig --pkg-end --pkg-begin upaya /Users/oli/Dev/zig-upaya/src/upaya.zig --pkg-begin stb_image /Users/oli/Dev/zig-upaya/src/deps/stb_image/stb_image.zig --pkg-end --pkg-begin filebrowser /Users/oli/Dev/zig-upaya/src/deps/filebrowser/filebrowser.zig --pkg-end --pkg-begin sokol /Users/oli/Dev/zig-upaya/src/deps/sokol/sokol.zig --pkg-end --pkg-begin imgui /Users/oli/Dev/zig-upaya/src/deps/imgui/imgui.zig --pkg-end --pkg-end --pkg-begin sokol /Users/oli/Dev/zig-upaya/src/deps/sokol/sokol.zig --pkg-end --pkg-begin stb_image /Users/oli/Dev/zig-upaya/src/deps/stb_image/stb_image.zig --pkg-end --pkg-begin imgui /Users/oli/Dev/zig-upaya/src/deps/imgui/imgui.zig --pkg-end --pkg-begin filebrowser /Users/oli/Dev/zig-upaya/src/deps/filebrowser/filebrowser.zig --pkg-end -I /Users/oli/Dev/zig-upaya/src -I /Users/oli/Dev/zig-upaya/src/deps/sokol -I /Users/oli/Dev/zig-upaya/src/deps/imgui -I /Users/oli/Dev/zig-upaya/src/deps/imgui/cimgui -F /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks -F /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks -framework Foundation -framework Cocoa -framework Quartz -framework QuartzCore -framework Metal -framework MetalKit -framework OpenGL -framework Audiotoolbox -framework CoreAudio --system-linker-hack --cache on

**Comment by jamesb93** [comment]
See https://github.com/prime31/zig-upaya/issues/4

**Comment by prime31** [comment]
You will need zig master due to a linker bug on macos with c++ code.
