### ISSUE TITLE
Support prefixes

### ISSUE THREAD

**Issue by zenith391** [prime31/zig-upaya#6]
I tried using `zig-upaya` with gitsubmodules, but there's one problem:
with your build system, you expect zig-upaya folder to always be in the `src` folder which of course, when used in any real app will break, it would be better to add some sort of `prefix` to where zig-upaya is located. As for now it gives a plenty error all related to the fact the Zig Build System wants to compile non-existing files.

So yea, please just add a `prefix` to add for using zig-upaya like a real library

**Comment by prime31** [comment]
Ahh, very good point. All the `linkArtifact` methods should take in a prefix.

**Comment by zenith391** [comment]
@prime31 any update on this?

**Comment by prime31** [comment]
I’ll see if I can slap it in there today.
